# Generated by Django 5.1.3 on 2025-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=20),
        ),
    ]
